### ISSUE TITLE
Do you have remote employees?

### ISSUE THREAD

**Issue by aitchabee** [github-archive/hr-opensource#22]
More than sixty percent of our company is remote. We are aware of the pros and cons of having remote work(ers), and are always looking for ways to improve collaboration with our remotes, and the quality of their work life.

We would like to know how other companies have shaped their policies and programs around remote workers.

In our case, we define remote as anyone who does not work out of our headquarters office. This includes people working at home, in co-working spaces, and in small offices of 2-6 people, both international and domestic.

We would like to know if you have remote workers.  If so, would you be willing to speak with us about your best practices. We would like to delve into specific policies you have including what expenditures you allow for travel, equipment, office space, etc., what tools you use to connect and collaborate with remotes, what kind of benefits/perks parity you have, etc. 

If you have two minutes, could you please fill out this survey?  Thank you so much for your time!

Link to the survey: https://docs.google.com/forms/d/1naWRB2yfGOohYcW8xnxSHdRQCLuikAKzWKqnwGR6IpU/viewform?usp=send_form

**Comment by kellidrag** [comment]
@Foggybtmgirl just realized we never posted the results here...should we before we :door: this? Does anyone care to see them?

Thx! :zap:

**Comment by ChrisLundquist** [comment]
I'd be interested.

**Comment by CrisBarrett** [comment]
I do

sent via mobile device

On Mar 1, 2015, at 3:55 PM, Kelli Dragovich <notifications@github.com<mailto:notifications@github.com>> wrote:


@Foggybtmgirl<https://github.com/Foggybtmgirl> just realized we never posted the results here...should we before we [https://assets-cdn.github.com/images/icons/emoji/unicode/1f6aa.png]  this? Does anyone care to see them?

Thx! [https://assets-cdn.github.com/images/icons/emoji/unicode/26a1.png]

**Comment by kellidrag** [comment]
:cool: @Foggybtmgirl can we post our aggregate trends/themes? Thx!

**Comment by Foggybtmgirl** [comment]
Hi All

I will try to keep this first pass short.  I will cover the big take-aways that might be applicable to all companies.  Please let me know if you want more data. On the whole, our remote employees reported having a good experience, but there was plenty of room for improvement as well. Beyond the items listed under "Potential Solutions" below, we now do a one hour session during on-boarding that specifically addresses why we are distributed, why we make asynchronous communication a priority, how to use our communication tools, and tips and tricks for being remote. 

**Significant Issues**:

* Communication:
    - Remote employees (RE) reported feeling overwhelmed by the number of sources of information they felt they must keep up with in order to understand company and team priorities. 
    - REs felt (at our larger size) that there was no longer an effective dialog about company and team direction.
    - REs felt that communication was not always respectful, in terms of both tone/inclusion, and also time zone awareness (not leaving longer work cycles to make sure everyone had a chance to collaborate).
    - REs felt it was sometimes hard to find information on internal company policies or procedures.
* Disconnectedness: 
    - REs felt it was hard to stay connected enough to have a good grasp on priorities.
    - REs reported lacking strong social connections that help them stay connected and form good working relationships with their teammates. They struggle to collaborate and be productive as a result.
* Growth:
    - REs were concerned there was no clear path for career growth as a remote.
* Healthy Space: 
    - REs reported being unsure of the process and procedures for maintaining a healthy work environment (procuring ergonomically sound furniture, moving into co-working space, etc.)

**Potential Solutions**
* Communication
    - Streamline communication sources. (We are still working on this, but have instituted a weekly TL;DR digest that has been well received and is always being iterated to include good information.)
    - Work with managers and internal communications to facilitate improved communications within teams and the company.
    - Help facilitate Learning & Development (Communications workshops and Manager training).
    - Ensure all processes and procedures are written down and discoverable.
    - Set good expectations about what we do and do not provide for remotes and what life is like at HQ. (This has included revising our Travel and Expense policies.)
* Connectedness
    - Work with managers to help communicate priorities, have effective 1:1s, and work on career pathing.
    - Help REs find social connections (improve mini-summits, hack-houses, travel opportunities, and social time while at HQ, and also include REs in Outreach events like Patchworks.)
    - Facilitate distributed means of REs getting to know each other and those at HQ.
* Growth
    - Determine areas/functions where remote managers make sense (maybe all? some?), and provide other growth opportunities like professional development workshops.
* Healthy Space
    - Provide a remote friendly ergonomic evaluation program
    - Work across departments to determine appropriate procedures around equipment and space spending.
