### ISSUE TITLE
Need HR for a great start up in India

### ISSUE THREAD

**Issue by Pmccord** [github-archive/hr-opensource#26]
This is from Kavin Mittal CEO of Hike (the Snapchat of India). He is a great young CEO with a rocket ship of a company. 

One of the roles I'm resetting is HR.  I'm looking fora self starter (like a CEO of HR)  I strongly believe that HR should be split into two and have gone ahead and done that:
1. Recruiting & Admin
2. People Operations

I've had one of my x-Product Heads take up #1 to bring a very different approach to recruiting and I can already see a big difference. The guys more pro-active and has opened up a ton of more un-conventional channels of finding people and is personally hunting them down. Admin now rolls up into my CFO.

On People Operations, this is a tricky one. The expectations are so high here that I'm wondering what kind of person I'll need. Ideally a CEO of HR who handles everything from organizational behavior to the appraisal process, has a deep understanding of industry and the business and is very strategic, helps us maintain and pro-actively build the culture and also keeps our managers and people in general to a very high standard.

This is such a large gap in the company today. I really want HR to have a seat on the table but I'm struggling to find someone with vision who can fill that seat.

I'd like find someone from the US whose spend some time at a FB, Google or seen this part of a business. Ideally someone who has ties back in India.

**Comment by kellidrag** [comment]
Did they find their hire @Pmccord ?
