### ISSUE TITLE
Two great HR roles in NYC

### ISSUE THREAD

**Issue by Pmccord** [github-archive/hr-opensource#27]
I'm in New York working with 2 really fun companies that are looking for great HR people. Ideally, they'd love to find the perfect Chief Talent person, but would be open to Director level folks too.

Warby Parker is an on-line glasses company. Phenomenal growth last year, looking to repeat it this year. They are a fascinating business because in addition to the NYC corporate employees (working on the tech, marketing, etc. ~100 folks) they have a customer service center in Kentucky and 10 retail stores around the country (growing that too). They just opened a store in on Hayes St. in SF. I really adore working with this team. Jana Rich is working with them on the search.

Harry's Shave is on-line razors and shave cream. Great brands, also killer growth. They are a quirky company in that they have ~70 people in their NYC start up and last year they bough a 100 year old razor blade manufacturing company in Germany (500 employees). Talk about an interesting integration! They ideally would like someone who speaks German and who would love the travel.

Let me know if you have any leads, ideas or interest.

thanks,

Patty

**Comment by kellidrag** [comment]
Will scrape my networks! Hey do that company in India ever find their HR leader?

**Comment by Pmccord** [comment]
I'm interviewing candidates for them this week, so...maybe.

**Comment by kellidrag** [comment]
:+1:

**Comment by bsteinbe** [comment]
I will as well.  Warby Parker would be amazing!  Wish it was in SF!

**Comment by Margowheel** [comment]
Super juicy- will definitely look at my network.

M.

**Comment by kellidrag** [comment]
I scraped mine @Pmccord and don't have anything real there, so sorry. Will let you know if anything pops up...
