### ISSUE TITLE
Looking for your thoughts on how you handle maternity leaves, vacations, anything other leaves

### ISSUE THREAD

**Issue by Margowheel** [github-archive/hr-opensource#28]
Hi all
I'd love to hear how you approach leaves of all kinds, particularly maternity and return to work. Also very interested in your approach to vacations. I got good info from this group on sabbaticals. Thanks in advance. 

Margo

**Comment by bsteinbe** [comment]
I asked this question as well.  I have a lot of data from my own research,
but really would like others to share!

On Mon, Feb 2, 2015 at 10:18 AM, Margowheel <notifications@github.com>
wrote:

> Hi all
> I'd love to hear how you approach leaves of all kinds, particularly
> maternity and return to work. Also very interested in your approach to
> vacations. I got good info from this group on sabbaticals. Thanks in
> advance.
>
> Margo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hr-opensource/issues/28>.
>



-- 
-Beth Steinberg
bethannsteinberg@gmail.com

**Comment by Margowheel** [comment]
Thanks Beth. Would love anything you have to share. I hope the transition
is going smoothly.

On Mon, Feb 2, 2015 at 10:26 AM, Beth Steinberg <notifications@github.com>
wrote:

> I asked this question as well. I have a lot of data from my own research,
> but really would like others to share!
>
> On Mon, Feb 2, 2015 at 10:18 AM, Margowheel <notifications@github.com>
> wrote:
>
> > Hi all
> > I'd love to hear how you approach leaves of all kinds, particularly
> > maternity and return to work. Also very interested in your approach to
> > vacations. I got good info from this group on sabbaticals. Thanks in
> > advance.
> >
> > Margo
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/github/hr-opensource/issues/28>.
> >
>
>
>
> --
> -Beth Steinberg
> bethannsteinberg@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hr-opensource/issues/28#issuecomment-72509605>.
>



-- 
Margaret Wheeler, Chief People and Culture Officer
Stitch Fix | your style. delivered.
731 Market Street, Suite 300
San Francisco, CA 94103
mwheeler@stitchfix.com
W: 206-310-3328
Are you bright, kind and goal oriented? We are hiring people just like
you! Check
us out <https://www.stitchfix.com/jobs>.

Feeling Social?  We are!  Facebook Twitter

**Comment by kellidrag** [comment]
Hey @Margowheel we have an uncapped vacation policy and rely on communication & accountability for that as far as what's needed & reasonable.  We have actually had the opposite issue than what you would think in that Hubbers don't take hardly any time at all, which we are trying to nudge them more to do so. 

Maternity and Paternity are the same in that we give 4 months off fully paid. 

Hope this helps! :+1:

**Comment by Margowheel** [comment]
Perfect! Thanks.

On Mon, Feb 2, 2015 at 5:03 PM, Kelli Dragovich <notifications@github.com>
wrote:

> Hey @Margowheel <https://github.com/Margowheel> we have an uncapped
> vacation policy and rely on communication & accountability for that as far
> as what's needed & reasonable. We have actually had the opposite issue than
> what you would think in that Hubbers don't take hardly any time at all,
> which we are trying to nudge them more to do so.
>
> Maternity and Paternity are the same in that we give 4 months off fully
> paid.
>
> Hope this helps! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hr-opensource/issues/28#issuecomment-72572408>.
>



-- 
Margaret Wheeler, Chief People and Culture Officer
Stitch Fix | your style. delivered.
731 Market Street, Suite 300
San Francisco, CA 94103
mwheeler@stitchfix.com
W: 206-310-3328
Are you bright, kind and goal oriented? We are hiring people just like
you! Check
us out <https://www.stitchfix.com/jobs>.

Feeling Social?  We are!  Facebook Twitter

**Comment by Maiton** [comment]
At RichRelevance (US only), we have unlimited vacation and sick time.  We want employees to take a break when they can and we want them to get better, at home, when they are sick.  We offer 3 months off for maternity and 1 month for paternity weaving all the different complications of the 3 state laws in which we have offices.  Overall, people don't take that much time off anymore (except in cases of parental leave) since they are always tethered to their iphones and other devices.  We get a lot of high morale marks for having these type of policies since employees feel empowered to do what's right to balance their work life with their personal life.  Plus, we have a pretty flexible work from home policy so it's worked out for us.  Finally, the managers who approve or don't approve certain instances usually become crucial ambassadors in staying consistent in how they make these decisions.  Train your managers on the purpose of the philosophy and they will create a win, win situation!

**Comment by Pmccord** [comment]
Love it!

Patty

**Comment by AlainaRestivo** [comment]
Hi all -

We are looking for insight into how others made a switch from a capped PTO policy to uncapped.  i.e., what did you do with employees who had accrued the maximum?  Did you feel like you also had to open up a more generous maternity and paternity policy?  and, lastly, did you still make people submit PTO requests via a system?  Thanks!
