### ISSUE TITLE
HR Team Ratio

### ISSUE THREAD

**Issue by srhr** [github-archive/hr-opensource#32]
Does anyone have good data on HR to employee ratio's now in the bay area?  Need the data to help with team build out requests (if you know specific company ratios that would help my case). Thank you!

**Comment by christineellis** [comment]
We use a few other measures like number of managers and location of employees, but generally we look at 1 HRBP per 300 employees at Facebook

**Comment by Maiton** [comment]
We follow finance standards who usually have 1 HR generalist to every 100 employees.

**Comment by kellidrag** [comment]
> We use a few other measures like number of managers and location of employees, but generally we look at 1 HRBP per 300 employees at Facebook

I love looking at the other pieces too @christineellis. The ratios really aren't enough data IMO to gage the right number of resources needed. Location, number of managers, the capabilities of those managers, the rate of org growth/hiring plan, and overall level of the type of HR work needed (are ya starting from scratch or do you have a well run org in place with pretty solid processes?) are super important to enter into that equation. :boom:
