### ISSUE TITLE
Equity refresh strategies

### ISSUE THREAD

**Issue by Margowheel** [github-archive/hr-opensource#33]
Hi all
Looking for some benchmarking on equity refresh strategies for private companies. Would love to connect. If you would like to you can email me directly at mwheeler@stitchfix.com

Thanks.

**Comment by CrisBarrett** [comment]
Margo,

This is one of the best posts I have ever read about this subject — http://firstround.com/review/The-Right-Way-to-Grant-Equity-to-Your-Employees/

We (Axcient) use a variation on the themes described there.

Happy to discuss live any time. 305.586.7509

Cris

Cris Barrett
VP, People & Places

[http://www.axcient.com/assets/logos/axcient-outlook-signature-logo.png]

O 650.933.9534
M 305.586.7509 (preferred)
cbarrett@axcient.com
www.axcient.com<http://www.axcient.com/>

No.1 fastest growing Security company in the U.S.<http://www.axcient.com/news-and-events/press-releases/axcient-forges-blistering-growth-path-in-business-continuity-and-disaster-recovery-market/>
No.4 fastest growing company in Silicon Valley<http://www.axcient.com/news-and-events/press-releases/axcient-forges-blistering-growth-path-in-business-continuity-and-disaster-recovery-market/>

**Comment by CrisBarrett** [comment]
Chris
Thanks so much. I really appreciate it.

M.

On Mon, Mar 23, 2015 at 4:22 PM, Cristopher Barrett <cbarrett@axcient.com>
wrote:

> Margo,
>
> This is one of the best posts I have ever read about this subject —
> http://firstround.com/review/The-Right-Way-to-Grant-Equity-to-Your-Employees
> /
>
> We (Axcient) use a variation on the themes described there.
>
> Happy to discuss live any time. 305.586.7509
>
> Cris
>
> *Cris Barrett*
> VP, People & Places
>
> O 650.933.9534
> M 305.586.7509 (preferred)
> cbarrett@axcient.com
> www.axcient.com
>
> *No.1 fastest growing Security company in the U.S.
> <http://www.axcient.com/news-and-events/press-releases/axcient-forges-blistering-growth-path-in-business-continuity-and-disaster-recovery-market/>*
> *No.4 fastest growing company in Silicon Valley
> <http://www.axcient.com/news-and-events/press-releases/axcient-forges-blistering-growth-path-in-business-continuity-and-disaster-recovery-market/>*
>
>
> From: Margowheel <notifications@github.com>
> Reply-To: github/hr-opensource <
> reply@reply.github.com
> >
> Date: Monday, March 23, 2015 at 4:19 PM
> To: github/hr-opensource <hr-opensource@noreply.github.com>
> Subject: [hr-opensource] Equity refresh strategies (#33)
>
> Hi all
> Looking for some benchmarking on equity refresh strategies for private
> companies. Would love to connect. If you would like to you can email me
> directly at mwheeler@stitchfix.com
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hr-opensource/issues/33>.
>



-- 
Margaret Wheeler, Chief People and Culture Officer
Stitch Fix | your style. delivered.
731 Market Street, Suite 300
San Francisco, CA 94103
mwheeler@stitchfix.com
W: 206-310-3328
Are you kind, bright and goal oriented? We are hiring people just like
you! Check
us out <https://www.stitchfix.com/jobs>.

Feeling Social?  We are!  Facebook Twitter
