### ISSUE TITLE
Stitch Fix is hiring People and Culture People

### ISSUE THREAD

**Issue by Margowheel** [github-archive/hr-opensource#38]
Hi all
I have two really incredible roles available on my team. Links included below. The director role will have a significant scope supporting our COO. This includes our very large and important Styling and Client Experience teams, as well as Creative, Marketing and Strategy. 
As for our Tech Recruiter, this has proven to be a unicorn hunt! Would love your ideas and any great candidates.

Thanks so much.

Margo

Tech Recruiter
https://www.ziprecruiter.com/jobs/stitch-fix-bee85f3b/technical-recruiter-9dbfce5c

Director People and Culture, Business Partner
https://www.ziprecruiter.com/jobs/stitch-fix-bee85f3b/director-people-and-culture-business-partner-65b0b8c3

**Comment by AlainaRestivo** [comment]
@Margowheel, are these positions 100% based in SF?

**Comment by Margowheel** [comment]
Hi Alaina
Thanks for reaching out. These positions are based in San Francisco at our
HQ.

Best,
Margo

On Mon, Jun 8, 2015 at 12:00 PM, AlainaRestivo <notifications@github.com>
wrote:

> @Margowheel <https://github.com/Margowheel>, are these positions 100%
> based in SF?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/hr-opensource/issues/38#issuecomment-110108165>
> .
>



-- 
Margaret Wheeler, Chief People and Culture Officer
Stitch Fix | your style. delivered.
731 Market Street, Suite 300
San Francisco, CA 94103
mwheeler@stitchfix.com
W: 206-310-3328
Are you kind, bright and goal oriented? We are hiring people just like
you! Check
us out <https://www.stitchfix.com/jobs>.

Feeling Social?  We are!  Facebook Twitter
