### ISSUE TITLE
Transitioning from accrued PTO to unlimited vacation

### ISSUE THREAD

**Issue by AlainaRestivo** [github-archive/hr-opensource#39]
Hi all -
We are looking for insight into how others made a switch from a capped PTO policy to uncapped. i.e., what did you do with employees who had accrued the maximum? Did you feel like you also had to open up a more generous maternity and paternity policy? and, lastly, did you still make people submit PTO requests via a system? Thanks!

**Comment by Pmccord** [comment]
Here is the Netflix policy document. Yes, you have to close the old program down on a certain date and pay out any accrued time off. The new Netflix Parental leave policy is mostly just an extension of the unlimited time off policy/practice.  No, I didn't have them submit requests to the system. Thats the whole point, you put time off in the hands of employees and their managers. Any leave longer than 30 days needed HR involvement. Also disability.

to make all of this work you need:

- Managers who manage projects and people closely and make sure delivery dates allow for people to take time and results are clear.
- Employees who are grown ups and self regulating. They can handle the freedom.
- Management that takes time off themselves. Employees pattern on who is in charge.
- HR that is VERY knowledgeable about projects and timelines and business deliverables. Your job is to ensure stuff gets done and folks get the time they need. Sometimes you need to teach them how to be more flexible
- think it through and communicate well

Well, I cant seem to insert the doc in this thread. I'll send it on email.

Good luck!

Patty

**Comment by Pmccord** [comment]
The Netflix time off doc

**Comment by kellidrag** [comment]
Agree with @Pmccord here @AlainaRestivo.

We are working on this currently at GitHub: 

> Managers who manage projects and people closely and make sure delivery dates allow for people to take time and results are clear.

We are making our policy more clear soon that taking time is an expectation. We have had the reverse issue across various parts of the company where folks aren't taking vacation. (A challenge/issue that I think is independent of whether you have a capped or an un capped policy actually).  

So, I think the whole topic is shifting into a new conversation vs. do you.should you have one type or policy or another.

**Comment by AlainaRestivo** [comment]
@kellidrag really appreciate the insight.  We loosely follow this already and our culture supports this.  We have some expense considerations (we have a high accrual cap, 4 weeks, and high balances across the org).  It might not be financially possible for us to pay all of those out on a certain date.  

We also want to make sure that we're paying attention to circumstances where people would be banking 4 weeks - e.g., parental leave.  I've read a few articles recently about challenges to unlimited policies where employees question why they can't take full paid leave for the entire FMLA period.  

I'm the first to admit that core benefits and policies aren't really my bag - I'm in the "we are all adults" camp - so hearing how others have navigated those circumstances would be helpful.

**Comment by CrisBarrett** [comment]
Alaina,

How about capping the current balances at a certain level v. just paying them out? Not all companies have enough IPO $ or recent VC or PE investment in the bank. :)

You could even reduce your liability by capping the accrued vacation at a lower amount than your current cap - eg as part of your communication re the program, tell people that the accrued cap will be X. And they have until Y date to use some of their accrued vacation or else they will lose it. 

Then, when each person resigns, you would pay X in accordance with the laws of their state (usually as part of their final check).

Cris 

sent via mobile device

**Comment by AlainaRestivo** [comment]
@CrisBarrett that's what I was thinking.  In RI, we must pay out all unused PTO in accordance with our policy, but the policy accrual cap can be 1 hr if we choose.  I'd like to start messaging this out along with our open enrollment changes at the start of the quarter, and then give to the end of the calendar year.  

New related question.  Is anyone doing quota relief for Sales teams?  Would be curios to see how that factors into this conversation.
