### ISSUE TITLE
Exec Coach recommendations

### ISSUE THREAD

**Issue by kellidrag** [github-archive/hr-opensource#4]
Hey all - who is great and for what niche's? 

Three referrals that I constantly get (I have met  Joan and Marcie but not Leila yet):

Leila: 
https://www.linkedin.com/profile/view?id=4844315&authType=OUT_OF_NETWORK&authToken=uPAr&locale=en_US&trk=tyah2&trkInfo=tarId%3A1402691771798%2Ctas%3Alei%2Cidx%3A2-3-4

Joan: 
https://www.linkedin.com/profile/view?id=53204&authType=OUT_OF_NETWORK&authToken=Xh2C&locale=en_US&trk=tyah2&trkInfo=tarId%3A1402691746681%2Ctas%3Ajoan%20da%2Cidx%3A2-1-2

Marcie: 
https://www.linkedin.com/profile/view?id=5902068&authType=OUT_OF_NETWORK&authToken=ILhB&locale=en_US&trk=tyah2&trkInfo=tarId%3A1402695310060%2Ctas%3Amarcie%2Cidx%3A2-1-2

**Comment by ghost** [comment]
Martin Karlsson Higgins:Majorna:Göteborg:3
